spring.application.name=OrderService

server.port=8083

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

management.endpoints.web.exposure.include=*

resilience4j.circuitbreaker.instances.orderServiceCB.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.orderServiceCB.slidingWindowSize=5
resilience4j.circuitbreaker.instances.orderServiceCB.minimumNumberOfCalls=1
resilience4j.circuitbreaker.instances.orderServiceCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.orderServiceCB.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.orderServiceCB.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.orderServiceCB.eventConsumerBufferSize=10
resilience4j.circuitbreaker.instances.orderServiceCB.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances.orderServiceCB.slidingWindowType=COUNT_BASED